### ISSUE TITLE
make generate script appears to be broken?

### ISSUE THREAD

**Issue by conorhub** [izniburak/demet#1]
After the first question to regenerate, it looks like **$answer** doesn't match the string the user provides? See:

```
user@server:~/docker/demet$ make generate
DEMET - Docker-Compose File Generating Tool

Docker-compose file has already been generated.
Do you want to regenerate it? [y|n] : y


Which webserver do you want to use? [apache|Nginx] (Default: apache) : nginx
./.demet/demet.sh: 19: [: nginx: unexpected operator
Okay, Apache will be used.

Which version of PHP do you want to use? (Default: 8) [7|8] : 7

./.demet/demet.sh: 28: [: 7: unexpected operator
Okay, PHP 8 will be used.
```

See above where 'nginx' and '7' are not recognised. I tried copying and pasting nginx from the script incase it was a character issue but same problem.

**Comment by Mohamed-Zhran-MD** [comment]
in demmet.sh replace == in if statements with = 
example 
if [ "$answer" != 'y' ];

**Comment by izniburak** [comment]
This issue has been fixed on last commits. Please update your repo files and try again.

**Comment by ademalidurmus** [comment]
It's still broken for me :/ I'm trying to fix it.
![image](https://user-images.githubusercontent.com/22513266/205501119-42478590-374f-4c54-b5bb-9d31fa17c6a5.png)

```
➜  demet git:(master) cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.3 (Una)"
```

**Comment by ademalidurmus** [comment]
`if [ "$answer" = 'y' ]; then` worked for me :) 

```
➜  demet git:(master) ✗ make generate
DEMET - Docker-Compose File Generating Tool

Docker-compose file has already been generated.
Do you want to regenerate it? [y|n] (Default: n) : y


Which webserver do you want to use? [apache|nginx] (Default: apache) : 
Okay, Apache will be used.

Which version of PHP do you want to use? (Default: 8.1) [7.4|8.0|8.1] : 
Okay, PHP 8.1 will be used.

Do you want to use MySQL/MariaDb? [y|n] (Default: n) : y
Which image do you want to use? [mysql|mariadb] (Default: mysql) : 
Okay, MySQL will be used.

Do you want to use PhpMyAdmin? [y|n] (Default: n) : y
Okay, PhpMyAdmin will be added.

Do you want to use PostgreSQL? [y|n] (Default: n) : n
Okay, PostgreSQL won't be added.
```
